title: "Neocrym"

email: "engineering@neocrym.com"

tagline: "Neocrym is a collection of open source projects."

description: "Neocrym is a collection of open source projects."

logo: "https://static.neocrym.com/images/neocrym/v2/1x/neocrym-circle-logo-black-on-transparent--1x.png"

#defaults:
#  - scope:
#      path: ""
#    values:
      # card preview image
#      image: ""

# card preview image
#image: ""

footer_content: 'Copyright &copy; 2020-2021 <a href="/">Neocrym Records Inc</a>.'

#destination: docs

permalink: pretty

baseurl: "" # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: neocrym

#twitter:
#  username: neocrym
#  card: summary_large_image
#  image: "https://provose.com/assets/images/1x/logo-black-on-transparent-1x.png"
  
github_username: neocrym

#color_scheme: provose

social:
  name: Neocrym Records Inc.
  links:
    - https://twitter.com/neocrym
    - https://www.facebook.com/neocrym
    - https://www.linkedin.com/company/neocrym
    - https://github.com/provose


#latest_provose_version: v4.0

# Build settings
#remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-sitemap
#  - jekyll-admin
  - jekyll-seo-tag

# Enable search: https://pmarsceill.github.io/just-the-docs/docs/search/
search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .git
  - .github
  - .jekyll-cache/
  - .sass-cache/
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docker-compose.yml
  - gemfiles/
  - node_modules/

